# Generated by Django 2.2 on 2020-04-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200417_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, max_length=6050, null=True, verbose_name='Текст публикации'),
        ),
    ]
