# Generated by Django 2.2 on 2020-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(default='0', max_length=220),
        ),
    ]
